apiVersion: v2
appVersion: "1.0.18-nvidia"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 14.0.1
description: M3U Proxy for Plex DVR and Emby Live TV.
home: https://github.com/dingfelder/charts/tree/master/charts/stable/threadfin
icon: https://github.com/Threadfin/Threadfin/raw/main/html/img/threadfin.png
keywords:
  - threadfin
  - xteve
  - iptv
  - plex
  - emby
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: threadfin
sources:
  - https://github.com/dingfelder/charts/tree/master/charts/stable/threadfin
  - https://github.com/threadfin/threadfin
  - https://hub.docker.com/r/fyb3roptik/threadfin
  - https://github.com/k8s-at-home/container-images
version: 10.0.0
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
